INSERT INTO Books (name, author_id, avg_rating, publ_date, isbn, lang_code, genre, num_pages, rating_count, review_count, publisher, image_link, description)
VALUES
('The Great Gatsby', 'F. Scott Fitzgerald', 4.2, '1925-04-10', '9780743273565', 'en', 'Classic', 180, 3987123, 58213, 'Scribner', 'https://example.com/gatsby.jpg', 'A novel about the American dream.Goodreads does not specify an exact total number of genres on its platform. While the Genres page highlights around 40 primary genres, users have the flexibility to create custom shelves, leading to a vast array of sub-genres and niche categories. This user-driven system means the number of genres is continually evolving and expanding. Therefore, it is challenging to provide a definitive count of all genres available on Goodreads.​'),
('To Kill a Mockingbird', 'Harper Lee', 4.3, '1960-07-11', '9780061120084', 'en', 'Classic', 281, 4859362, 78921, 'J.B. Lippincott & Co.', 'https://example.com/mockingbird.jpg', 'A novel about racial injustice in the American South.'),
('1984', 'George Orwell', 4.4, '1949-06-08', '9780451524935', 'en', 'Dystopian', 328, 5783621, 96523, 'Secker & Warburg', 'https://example.com/1984.jpg', 'A dystopian novel about totalitarianism.'),
('Pride and Prejudice', 'Jane Austen', 4.5, '1813-01-28', '9780141439518', 'en', 'Romance', 279, 5983621, 87546, 'T. Egerton', 'https://example.com/pride.jpg', 'A classic romance novel.'),
('Moby-Dick', 'Herman Melville', 3.9, '1851-10-18', '9781503280786', 'en', 'Adventure', 635, 1287364, 23612, 'Harper & Brothers', 'https://example.com/mobydick.jpg', 'A whaling adventure novel.'),
('The Night Circus', 'Erin Morgenstern', 4.2, '2011-09-13', '9780385534635', 'en', 'Fantasy', 387, 367491, 15492, 'Doubleday', 'https://example.com/nightcircus.jpg', 'A magical competition between two young illusionists.'),
('The Catcher in the Rye', 'J.D. Salinger', 4.0, '1951-07-16', '9780316769488', 'en', 'Classic', 277, 3456721, 65432, 'Little, Brown and Company', 'https://example.com/catcher.jpg', 'A story about teenage rebellion and angst.'),
('The Hobbit', 'J.R.R. Tolkien', 4.7, '1937-09-21', '9780547928227', 'en', 'Fantasy', 310, 4893621, 78945, 'George Allen & Unwin', 'https://example.com/hobbit.jpg', 'A fantasy adventure about a hobbit named Bilbo Baggins.'),
('The Alchemist', 'Paulo Coelho', 4.3, '1988-05-01', '9780061122415', 'en', 'Philosophical', 208, 2345678, 54321, 'HarperOne', 'https://example.com/alchemist.jpg', 'A journey of self-discovery and following ones dreams.'),
('The Road', 'Cormac McCarthy', 4.1, '2006-09-26', '9780307387899', 'en', 'Post-Apocalyptic', 287, 1567892, 32145, 'Alfred A. Knopf', 'https://example.com/road.jpg', 'A father and son journey through a desolate world.'),
('The Book Thief', 'Markus Zusak', 4.4, '2005-03-14', '9780375842207', 'en', 'Historical Fiction', 552, 2789345, 65478, 'Picador', 'https://example.com/bookthief.jpg', 'A story about a young girl in Nazi Germany who finds solace in stealing books.');

INSERT INTO Genres (genre_name, description)
VALUES
('Classic', 'Timeless works of literature that have stood the test of time.'),
('Dystopian', 'Fictional societies that are undesirable or frightening.'),
('Romance', 'Stories centered around love and relationships.'),
('Adventure', 'Exciting tales of exploration and daring journeys.'),
('Fantasy', 'Fictional worlds with magical or supernatural elements.'),
('Philosophical', 'Books that explore deep questions about life and existence.'),
('Post-Apocalyptic', 'Stories set in a world after a catastrophic event.'),
('Historical Fiction', 'Fictional stories set in historical settings.'),
('Science Fiction', 'Fiction based on futuristic or scientific concepts.'),
('Mystery', 'Stories involving solving a crime or uncovering secrets.'),
('Thriller', 'Fast-paced stories with suspense and excitement.'),
('Horror', 'Fiction designed to scare or unsettle the reader.'),
('Biography', 'The life story of a person written by someone else.'),
('Autobiography', 'The life story of a person written by themselves.'),
('Self-Help', 'Books aimed at personal development and improvement.'),
('Young Adult', 'Books targeted at teenage readers.'),
('Poetry', 'Literary works written in verse.'),
('Drama', 'Stories with intense emotional themes and conflicts.'),
('Humor', 'Books designed to entertain and amuse the reader.'),
('Graphic Novel', 'Stories told through a combination of illustrations and text.'),
('Memoir', 'A personal account of specific experiences in the author’s life.'),
('Crime', 'Stories focused on criminal activities and their consequences.'),
('Spirituality', 'Books exploring spiritual beliefs and practices.'),
('Travel', 'Books about journeys and exploration of different places.'),
('Cooking', 'Books containing recipes and culinary techniques.'),
('Health & Fitness', 'Books focused on physical and mental well-being.'),
('Politics', 'Books discussing political systems, ideologies, and events.'),
('Economics', 'Books exploring financial systems and economic theories.'),
('Art', 'Books about visual arts, techniques, and history.');