INSERT INTO genre (genre_name) VALUES ('Fiction');
INSERT INTO genre (genre_name) VALUES ('Fantasy');
INSERT INTO genre (genre_name) VALUES ('Audiobook');
INSERT INTO genre (genre_name) VALUES ('Romance');
INSERT INTO genre (genre_name) VALUES ('Young Adult');
INSERT INTO genre (genre_name) VALUES ('Mystery');
INSERT INTO genre (genre_name) VALUES ('Classics');
INSERT INTO genre (genre_name) VALUES ('Contemporary');
INSERT INTO genre (genre_name) VALUES ('Historical Fiction');
INSERT INTO genre (genre_name) VALUES ('Book Club');
INSERT INTO genre (genre_name) VALUES ('Thriller');
INSERT INTO genre (genre_name) VALUES ('Nonfiction');
INSERT INTO genre (genre_name) VALUES ('Science Fiction');
INSERT INTO genre (genre_name) VALUES ('Adventure');
INSERT INTO genre (genre_name) VALUES ('Paranormal');
INSERT INTO genre (genre_name) VALUES ('Crime');
INSERT INTO genre (genre_name) VALUES ('Literature');
INSERT INTO genre (genre_name) VALUES ('Historical');
INSERT INTO genre (genre_name) VALUES ('Childrens');
INSERT INTO genre (genre_name) VALUES ('Mystery Thriller');
INSERT INTO genre (genre_name) VALUES ('Novels');
INSERT INTO genre (genre_name) VALUES ('Humor');
INSERT INTO genre (genre_name) VALUES ('Suspense');
INSERT INTO genre (genre_name) VALUES ('Adult');
INSERT INTO genre (genre_name) VALUES ('Horror');
INSERT INTO genre (genre_name) VALUES ('Chick Lit');
INSERT INTO genre (genre_name) VALUES ('Middle Grade');
INSERT INTO genre (genre_name) VALUES ('Biography');
INSERT INTO genre (genre_name) VALUES ('Magic');
INSERT INTO genre (genre_name) VALUES ('Science Fiction Fantasy');
INSERT INTO genre (genre_name) VALUES ('Urban Fantasy');
INSERT INTO genre (genre_name) VALUES ('Memoir');
INSERT INTO genre (genre_name) VALUES ('Vampires');
INSERT INTO genre (genre_name) VALUES ('Literary Fiction');
INSERT INTO genre (genre_name) VALUES ('History');
INSERT INTO genre (genre_name) VALUES ('High Fantasy');
INSERT INTO genre (genre_name) VALUES ('Paranormal Romance');
INSERT INTO genre (genre_name) VALUES ('Dystopia');
INSERT INTO genre (genre_name) VALUES ('Philosophy');
INSERT INTO genre (genre_name) VALUES ('Graphic Novels');
INSERT INTO genre (genre_name) VALUES ('Realistic Fiction');
INSERT INTO genre (genre_name) VALUES ('Adult Fiction');
INSERT INTO genre (genre_name) VALUES ('Epic Fantasy');
INSERT INTO genre (genre_name) VALUES ('Short Stories');
INSERT INTO genre (genre_name) VALUES ('Contemporary Romance');
INSERT INTO genre (genre_name) VALUES ('Comics');
INSERT INTO genre (genre_name) VALUES ('Supernatural');
INSERT INTO genre (genre_name) VALUES ('Psychology');
INSERT INTO genre (genre_name) VALUES ('School');
INSERT INTO genre (genre_name) VALUES ('Animals');
INSERT INTO genre (genre_name) VALUES ('Self Help');
INSERT INTO genre (genre_name) VALUES ('Comedy');
INSERT INTO genre (genre_name) VALUES ('Biography Memoir');
INSERT INTO genre (genre_name) VALUES ('Science');
INSERT INTO genre (genre_name) VALUES ('Picture Books');
INSERT INTO genre (genre_name) VALUES ('American');
INSERT INTO genre (genre_name) VALUES ('War');
INSERT INTO genre (genre_name) VALUES ('Graphic Novels Comics');
INSERT INTO genre (genre_name) VALUES ('Politics');
INSERT INTO genre (genre_name) VALUES ('Religion');
INSERT INTO genre (genre_name) VALUES ('Detective');
INSERT INTO genre (genre_name) VALUES ('Poetry');
INSERT INTO genre (genre_name) VALUES ('Autobiography');
